# PostgreSQL configuration for all environments
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default

test:
  <<: *default
  database: portfolio_test

production:
  primary:
    <<: *default
    prepared_statements: false
    statement_limit: 0
  cache:
    <<: *default
    prepared_statements: false
    statement_limit: 0
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    prepared_statements: false
    statement_limit: 0
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    prepared_statements: false
    statement_limit: 0
    migrations_paths: db/cable_migrate
